name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.x'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-version }} ${{ matrix.dependencies}}'
        runs-on: ubuntu-22.04
        env:
            SYMFONY_PHPUNIT_VERSION: 9
            SYMFONY_DEPRECATIONS_HELPER: "/.*each.*/"
            SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.1'
                      dependencies: 'lowest'
                    - php-version: '8.1'
                    - php-version: '8.2'
                    - php-version: '8.3'
                      symfony-version: 6.4.*
                    - php-version: '8.3'

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2,flex'

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Execute test cases
              run: make test
